spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mariadb://${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: create
    generate-ddl: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  packages-to-scan: site.workforus.forus
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:sql/data.sql
#      schema-locations: classpath:sql/schema.sql

jwt:
  secret:
    key: ${jwt_secret_key}

---

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MariaDB;
    username: SA
    password:
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: always

jwt:
  secret:
    key: hellonicetomeetyouimmoerntoujoursthankyou