name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up environment variables
      run: |
        datasource_url=${{ secrets.DATASOURCE_URL }}
        datasource_username=${{ secrets.DATASOURCE_USERNAME }}
        datasource_password=${{ secrets.DATASOURCE_PASSWORD }}
        jwt_secret_key=${{ secrets.JWT_SECRET_KEY }}
        echo "$datasource_url"
        echo "datasource_url=$datasource_url" >> $GITHUB_ENV
        echo "$datasource_username"
        echo "datasource_username=$datasource_username" >> $GITHUB_ENV
        echo "$datasource_password"
        echo "datasource_password=$datasource_password" >> $GITHUB_ENV
        echo "$jwt_secret_key"
        echo "jwt_secret_key=$jwt_secret_key" >> $GITHUB_ENV
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
  docker:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.DOCKER_REPO }}:latest,${{ secrets.DOCKER_REPO }}:${GITHUB_RUN_ID}
